In [23]:
#1
import numpy as np
array = np.array([1, 3, 7, 1, 2])
indices = np.argmax(array)
print(indices) 


2


In [25]:
#2
import numpy as np
array = np.array([1, 3, 7, 1, 2])
indices = np.argmin(array)
print(indices)  


0


In [27]:
#3
import numpy as np
array = np.array([1, 2, 3], dtype=np.float32)
print(array)  
print(array.dtype)  


[1. 2. 3.]
float32


In [29]:
#4
import numpy as np
array = np.array([1.5, 2.5, 3.5])
new_array = array.astype(np.int32)
print(new_array)  
print(new_array.dtype)  


[1 2 3]
int32


In [31]:
#5
import numpy as np
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])
result = A + B
print(result)  


[[ 6  8]
 [10 12]]


In [33]:
#6
import numpy as np
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])
result = np.dot(A, B)
print(result)  

[[19 22]
 [43 50]]


In [35]:
#7
import numpy as np
matrix = np.array([[1, 2], [3, 4]])
transpose = np.transpose(matrix)
print(transpose)  


[[1 3]
 [2 4]]


In [37]:
#8
import numpy as np
array = np.array([1, 2, 3, 4, 5])
slice = array[1:4]
print(slice)


[2 3 4]


In [39]:
#9
import numpy as np
array = np.arange(0, 10, 2)
print(array) 


[0 2 4 6 8]


In [41]:
#10
import numpy as np
array = np.array([1, 2, 3, 4, 5, 6])
sub_arrays = np.split(array, 3)
print(sub_arrays)  

[array([1, 2]), array([3, 4]), array([5, 6])]
